import pygame

from pygame.locals import *

FPS = 40

WINDOWS_WIDTH = 1000

WINDOWS_HEIGHT = 700

WINDOWS_SIZE = (WINDOWS_WIDTH,WINDOWS_HEIGHT)

SCREENRECT = Rect(0, 0, WINDOWS_WIDTH, WINDOWS_HEIGHT)

SCORE = 0